# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AstrocloudAT0_0_3Dev < Formula
  desc "To build and run Airflow DAGs locally, deploy DAGs to the Astronomer Cloud and interact with the Astronomer API."
  homepage "https://astronomer.io"
  version "0.0.3-dev"

  on_macos do
    if Hardware::CPU.arm?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v0.0.3-dev/cloud-cli_0.0.3-dev_Darwin_arm64.tar.gz"
      sha256 "2a9c53d03b50c99dede0cc8c5f58b616f1473f0232d1d1d23cc1f2cf23f10ccd"

      def install
        bin.install "astrocloud"
      end
    end
    if Hardware::CPU.intel?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v0.0.3-dev/cloud-cli_0.0.3-dev_Darwin_x86_64.tar.gz"
      sha256 "4323cbbe6225d12c65aba205d989bbb6bb7e14562c241728be601d70ef88205b"

      def install
        bin.install "astrocloud"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v0.0.3-dev/cloud-cli_0.0.3-dev_Linux_arm64.tar.gz"
      sha256 "ca4b55aa5a7c88734ebea8d94477d43f124df4de8faca829c4d2c39391a7c075"

      def install
        bin.install "astrocloud"
      end
    end
    if Hardware::CPU.intel?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v0.0.3-dev/cloud-cli_0.0.3-dev_Linux_x86_64.tar.gz"
      sha256 "7d23933b5c49510fe0f470ad73f4af2298211b01b42029f28cd9c4762fe56fc5"

      def install
        bin.install "astrocloud"
      end
    end
  end

  test do
    system "#{bin}/astrocloud version"
  end
end
