# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AstrocloudAT1_3_1Stage < Formula
  desc "To build and run Airflow DAGs locally, deploy DAGs to the Astronomer Cloud and interact with the Astronomer API."
  homepage "https://astronomer.io"
  version "1.3.1-stage"

  on_macos do
    if Hardware::CPU.arm?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v1.3.1-stage/cloud-cli_1.3.1-stage_Darwin_arm64.tar.gz"
      sha256 "499b3c14d1a3cef2d635d5b75ff8443ef1c2b6f6ee8cee0302d711a4794f4057"

      def install
        bin.install "astrocloud"
      end
    end
    if Hardware::CPU.intel?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v1.3.1-stage/cloud-cli_1.3.1-stage_Darwin_x86_64.tar.gz"
      sha256 "edf888802b092215d0e4d5e1aedf4ae85d5c046605dd730f49fc00ab560eba76"

      def install
        bin.install "astrocloud"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v1.3.1-stage/cloud-cli_1.3.1-stage_Linux_arm64.tar.gz"
      sha256 "0234b17f92afc6473af3b2b771b4675d53e394c20e51bf49c92fdf8924687138"

      def install
        bin.install "astrocloud"
      end
    end
    if Hardware::CPU.intel?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v1.3.1-stage/cloud-cli_1.3.1-stage_Linux_x86_64.tar.gz"
      sha256 "bcd06ac7ec3b48241d993e3917d41d0d30335c0a65add52bf45c95c661c80705"

      def install
        bin.install "astrocloud"
      end
    end
  end

  test do
    system "#{bin}/astrocloud version"
  end
end
