# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AstrocloudAT134 < Formula
  desc "To build and run Airflow DAGs locally, deploy DAGs to the Astronomer Cloud and interact with the Astronomer API."
  homepage "https://astronomer.io"
  version "1.3.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v1.3.4/cloud-cli_1.3.4_Darwin_arm64.tar.gz"
      sha256 "9257b25577b8e74a9105d9ecade9123bd2e130f7c00d4013fc85b3caf169df85"

      def install
        bin.install "astrocloud"
      end
    end
    if Hardware::CPU.intel?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v1.3.4/cloud-cli_1.3.4_Darwin_x86_64.tar.gz"
      sha256 "8fa291e7c53e851560686bc4d60989fb4063cfbfd293da5a29fb9bd0879e0a1e"

      def install
        bin.install "astrocloud"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v1.3.4/cloud-cli_1.3.4_Linux_arm64.tar.gz"
      sha256 "64501d5e43008b9c23fc80d0fa9ecd2c1adc36f0e51704105229302789995ba2"

      def install
        bin.install "astrocloud"
      end
    end
    if Hardware::CPU.intel?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v1.3.4/cloud-cli_1.3.4_Linux_x86_64.tar.gz"
      sha256 "52f95aea910cc6c31dc2109e103b667e144b56c6d00436ff0b343a0dc40df9d2"

      def install
        bin.install "astrocloud"
      end
    end
  end

  test do
    system "#{bin}/astrocloud version"
  end
end
