# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AstrocloudATstage1_3_4 < Formula
  desc "To build and run Airflow DAGs locally, deploy DAGs to the Astronomer Cloud and interact with the Astronomer API."
  homepage "https://astronomer.io"
  version "1.3.4-stage2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v1.3.4-stage2/cloud-cli_1.3.4-stage2_Darwin_arm64.tar.gz"
      sha256 "6586af90031a10460f2bc1d4920aecde07c40e7a6be15ecb93a11269bcf7dedd"

      def install
        bin.install "astrocloud"
      end
    end
    if Hardware::CPU.intel?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v1.3.4-stage2/cloud-cli_1.3.4-stage2_Darwin_x86_64.tar.gz"
      sha256 "77ae1ddcfe00d90031a19a56363ac5871d7d31957ebac17e74468cd813466599"

      def install
        bin.install "astrocloud"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v1.3.4-stage2/cloud-cli_1.3.4-stage2_Linux_arm64.tar.gz"
      sha256 "2e30ccdd2e8007128c1013d1c0a9a6255845655f3f6676fa5c5509f258dc676d"

      def install
        bin.install "astrocloud"
      end
    end
    if Hardware::CPU.intel?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v1.3.4-stage2/cloud-cli_1.3.4-stage2_Linux_x86_64.tar.gz"
      sha256 "61d61084e5c6feac2360e41243ed86fe4073e35e2465b05b6ef3148929a70aa7"

      def install
        bin.install "astrocloud"
      end
    end
  end

  test do
    system "#{bin}/astrocloud version"
  end
end
