# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Astrocloud < Formula
  desc "To build and run Airflow DAGs locally, deploy DAGs to the Astronomer Cloud and interact with the Astronomer API."
  homepage "https://astronomer.io"
  version "0.5.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://go-releaser-astro-cloud.s3.amazonaws.com/releases/v0.5.0/cloud-cli_0.5.0_Darwin_arm64.tar.gz"
      sha256 "175d17d9ed629af34a0b51cf2d3d24fbe8e5d333e2f1820ced8e925f0085a34e"

      def install
        bin.install "astrocloud"
      end
    end
    if Hardware::CPU.intel?
      url "https://go-releaser-astro-cloud.s3.amazonaws.com/releases/v0.5.0/cloud-cli_0.5.0_Darwin_x86_64.tar.gz"
      sha256 "3921db996d0b7aaa843748c2dfea81fda6fdc21e530c44d7628ebf2b618a2ca2"

      def install
        bin.install "astrocloud"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://go-releaser-astro-cloud.s3.amazonaws.com/releases/v0.5.0/cloud-cli_0.5.0_Linux_arm64.tar.gz"
      sha256 "109ec29354c995fef4ce24cc602427f71cc45548a6712b048c717755ffbb4e61"

      def install
        bin.install "astrocloud"
      end
    end
    if Hardware::CPU.intel?
      url "https://go-releaser-astro-cloud.s3.amazonaws.com/releases/v0.5.0/cloud-cli_0.5.0_Linux_x86_64.tar.gz"
      sha256 "c11885d54b49e6559d822a773da5053eb6ed22ae3da9741e3fa9e283373d89e2"

      def install
        bin.install "astrocloud"
      end
    end
  end

  test do
    system "#{bin}/astrocloud version"
  end
end
