# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AstrocloudATstage134 < Formula
  desc "To build and run Airflow DAGs locally, deploy DAGs to the Astronomer Cloud and interact with the Astronomer API."
  homepage "https://astronomer.io"
  version "1.3.4-stage"

  on_macos do
    if Hardware::CPU.arm?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v1.3.4-stage/cloud-cli_1.3.4-stage_Darwin_arm64.tar.gz"
      sha256 "d35f64ae1c4e34a82268296eb52b8f895b0ef98218c24d8f6735023f11c43eec"

      def install
        bin.install "astrocloud"
      end
    end
    if Hardware::CPU.intel?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v1.3.4-stage/cloud-cli_1.3.4-stage_Darwin_x86_64.tar.gz"
      sha256 "dfe80daeabf45c7ada72e07c238ea62bd02ac3978879e20c9119df3cbd14385e"

      def install
        bin.install "astrocloud"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v1.3.4-stage/cloud-cli_1.3.4-stage_Linux_arm64.tar.gz"
      sha256 "12ad14e89dea975b05a3319455f8583ed883e427bc3a952ff4ce5518b469c8a7"

      def install
        bin.install "astrocloud"
      end
    end
    if Hardware::CPU.intel?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v1.3.4-stage/cloud-cli_1.3.4-stage_Linux_x86_64.tar.gz"
      sha256 "2544c4adc9fa94c03e2a60d54ad13bb6a39adcb5bd10d373bb548c832c1cc3b3"

      def install
        bin.install "astrocloud"
      end
    end
  end

  test do
    system "#{bin}/astrocloud version"
  end
end
