# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AstrocloudAT0_0_3Dev < Formula
  desc "To build and run Airflow DAGs locally, deploy DAGs to the Astronomer Cloud and interact with the Astronomer API."
  homepage "https://astronomer.io"
  version "0.0.3-dev"

  on_macos do
    if Hardware::CPU.arm?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v0.0.3-dev/cloud-cli_0.0.3-dev_Darwin_arm64.tar.gz"
      sha256 "1f13e1d76f8f535e45c0dad381bd1f3821029a80acb7e3cd1bdefd20e409e30a"

      def install
        bin.install "astrocloud"
      end
    end
    if Hardware::CPU.intel?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v0.0.3-dev/cloud-cli_0.0.3-dev_Darwin_x86_64.tar.gz"
      sha256 "477259e4ba0345add7fd7652d90346751d5cf140ce6fc88ec7c4f9610bda2dec"

      def install
        bin.install "astrocloud"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v0.0.3-dev/cloud-cli_0.0.3-dev_Linux_arm64.tar.gz"
      sha256 "c87da0dd154ec57aaed8a0c146fc8af6e6b439f83fa38d14738f4f6266470e11"

      def install
        bin.install "astrocloud"
      end
    end
    if Hardware::CPU.intel?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v0.0.3-dev/cloud-cli_0.0.3-dev_Linux_x86_64.tar.gz"
      sha256 "4e4741ba0872dd29d9e4cdc79c54b43711d205ca127604adbf8459f2e2bb549d"

      def install
        bin.install "astrocloud"
      end
    end
  end

  test do
    system "#{bin}/astrocloud version"
  end
end
