# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AstrocloudAT150Stage < Formula
  desc "To build and run Airflow DAGs locally, deploy DAGs to the Astronomer Cloud and interact with the Astronomer API."
  homepage "https://astronomer.io"
  version "1.5.0-stage"

  on_macos do
    if Hardware::CPU.arm?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v1.5.0-stage/cloud-cli_1.5.0-stage_Darwin_arm64.tar.gz"
      sha256 "a85b30b705bbeb0a5d3cce7aeee81c4b53f8a56ace61cb44226e9cce146e4027"

      def install
        bin.install "astrocloud"
      end
    end
    if Hardware::CPU.intel?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v1.5.0-stage/cloud-cli_1.5.0-stage_Darwin_x86_64.tar.gz"
      sha256 "8596229ed3fea526ce18afcc2e0bd69670e6e04361deac52134994602506f145"

      def install
        bin.install "astrocloud"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v1.5.0-stage/cloud-cli_1.5.0-stage_Linux_arm64.tar.gz"
      sha256 "d3cad477aec0c65ebae185872b068d251d923178142e65828240e7796f3db7f5"

      def install
        bin.install "astrocloud"
      end
    end
    if Hardware::CPU.intel?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v1.5.0-stage/cloud-cli_1.5.0-stage_Linux_x86_64.tar.gz"
      sha256 "461a5021f0ec7a30c134fbfc540690690d459690c140152d761f83061d509d46"

      def install
        bin.install "astrocloud"
      end
    end
  end

  test do
    system "#{bin}/astrocloud version"
  end
end
