# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AstrocloudAT001Alpha < Formula
  desc "To build and run Airflow DAGs locally, deploy DAGs to the Astronomer Cloud and interact with the Astronomer API."
  homepage "https://astronomer.io"
  version "0.0.1-alpha"

  on_macos do
    if Hardware::CPU.arm?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v0.13.0/cloud-cli_0.13.0_Darwin_arm64.tar.gz"
      sha256 "673bdb41499b0a21b6a410ea6148a44195af21e56cd41d83193a07fa33fc1b01"

      def install
        bin.install "astrocloud"
      end
    end
    if Hardware::CPU.intel?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v0.13.0/cloud-cli_0.13.0_Darwin_x86_64.tar.gz"
      sha256 "ae66747e0e4f71f5f8210370a4a9b2cd5914bb6fbdcdb76cf0fc21893d0f7ea1"

      def install
        bin.install "astrocloud"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v0.13.0/cloud-cli_0.13.0_Linux_arm64.tar.gz"
      sha256 "57b011b5dec2f04722ed923fa69a31f90ace7f8a86b2c2cb84301b4d1fa53fbf"

      def install
        bin.install "astrocloud"
      end
    end
    if Hardware::CPU.intel?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v0.13.0/cloud-cli_0.13.0_Linux_x86_64.tar.gz"
      sha256 "ce672b0a2a86408cae4ed0057c3a1fde3926f218f8b79f22bee05e4a509055a2"

      def install
        bin.install "astrocloud"
      end
    end
  end

  test do
    system "#{bin}/astrocloud version"
  end
end
