# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AstrocloudAT120Stage < Formula
  desc "To build and run Airflow DAGs locally, deploy DAGs to the Astronomer Cloud and interact with the Astronomer API."
  homepage "https://astronomer.io"
  version "1.2.0-stage"

  on_macos do
    if Hardware::CPU.arm?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v1.2.0-stage/cloud-cli_1.2.0-stage_Darwin_arm64.tar.gz"
      sha256 "5a56cf472e8ce76550489d35203bfdf5af5a85a4eae08d584c7b3287aa72e1ad"

      def install
        bin.install "astrocloud"
      end
    end
    if Hardware::CPU.intel?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v1.2.0-stage/cloud-cli_1.2.0-stage_Darwin_x86_64.tar.gz"
      sha256 "865ea143e4dae674fc82838f560f5abd50e4c3a0e4eb0dff64640f0438cecb2d"

      def install
        bin.install "astrocloud"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v1.2.0-stage/cloud-cli_1.2.0-stage_Linux_arm64.tar.gz"
      sha256 "21f230fbb887a3d0046ff6dc56c9dcb296d024900884dfb3297dd3af48dea5de"

      def install
        bin.install "astrocloud"
      end
    end
    if Hardware::CPU.intel?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v1.2.0-stage/cloud-cli_1.2.0-stage_Linux_x86_64.tar.gz"
      sha256 "94ae6d3de2f179e05d3e669a756a7bd5ad4dfdca89d8e2743171c4bbdfb0479a"

      def install
        bin.install "astrocloud"
      end
    end
  end

  test do
    system "#{bin}/astrocloud version"
  end
end
