# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AstrocloudAT1_1_0Test < Formula
  desc "To build and run Airflow DAGs locally, deploy DAGs to the Astronomer Cloud and interact with the Astronomer API."
  homepage "https://astronomer.io"
  version "1.1.0-test"

  on_macos do
    if Hardware::CPU.arm?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v1.1.0-test/cloud-cli_1.1.0-test_Darwin_arm64.tar.gz"
      sha256 "b33b43e81417ca45e44401859c313e67460ad4473c8af63c1e5928766d887848"

      def install
        bin.install "astrocloud"
      end
    end
    if Hardware::CPU.intel?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v1.1.0-test/cloud-cli_1.1.0-test_Darwin_x86_64.tar.gz"
      sha256 "91d7d89dbeebafb9230afe34cac4ad776de65430c0fa1f4c43fddf7c0c35310e"

      def install
        bin.install "astrocloud"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v1.1.0-test/cloud-cli_1.1.0-test_Linux_arm64.tar.gz"
      sha256 "cd00e6dd5300f0871229a674e596c759efa8ef76e6564ad1e4dc2f7b38f1207e"

      def install
        bin.install "astrocloud"
      end
    end
    if Hardware::CPU.intel?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v1.1.0-test/cloud-cli_1.1.0-test_Linux_x86_64.tar.gz"
      sha256 "38551f2781b637f60f5d065f47b9d3c1be0bcea6d066ae9932bb5073e17957cf"

      def install
        bin.install "astrocloud"
      end
    end
  end

  test do
    system "#{bin}/astrocloud version"
  end
end
