# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AstrocloudAT1_3_3Stage < Formula
  desc "To build and run Airflow DAGs locally, deploy DAGs to the Astronomer Cloud and interact with the Astronomer API."
  homepage "https://astronomer.io"
  version "1.3.3-stage"

  on_macos do
    if Hardware::CPU.arm?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v1.3.3-stage/cloud-cli_1.3.3-stage_Darwin_arm64.tar.gz"
      sha256 "8a8af9fc6ba10ef133cbfaaa0c6f52361b917c130095aa5ace9ee180e173217e"

      def install
        bin.install "astrocloud"
      end
    end
    if Hardware::CPU.intel?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v1.3.3-stage/cloud-cli_1.3.3-stage_Darwin_x86_64.tar.gz"
      sha256 "9fa1390b92cf4e7b287e9cca12542400d90177d6633dbe3a8801ff172762fdfc"

      def install
        bin.install "astrocloud"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v1.3.3-stage/cloud-cli_1.3.3-stage_Linux_arm64.tar.gz"
      sha256 "fec8ba5360bba16e7f132d14d2fbe5910cba849e42fa1398ed3dc8966ef9a819"

      def install
        bin.install "astrocloud"
      end
    end
    if Hardware::CPU.intel?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v1.3.3-stage/cloud-cli_1.3.3-stage_Linux_x86_64.tar.gz"
      sha256 "2103db1b1a7959d0c7b8ce8618e641422c990395e2db8e2ba27a7983ec4ad139"

      def install
        bin.install "astrocloud"
      end
    end
  end

  test do
    system "#{bin}/astrocloud version"
  end
end
