# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AstrocloudAT132Stage < Formula
  desc "To build and run Airflow DAGs locally, deploy DAGs to the Astronomer Cloud and interact with the Astronomer API."
  homepage "https://astronomer.io"
  version "1.3.2-stage"

  on_macos do
    if Hardware::CPU.arm?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v1.3.2-stage/cloud-cli_1.3.2-stage_Darwin_arm64.tar.gz"
      sha256 "dd33c373eb4802c12764f6de02cdc1bc21b08f8762c385cda423243626785456"

      def install
        bin.install "astrocloud"
      end
    end
    if Hardware::CPU.intel?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v1.3.2-stage/cloud-cli_1.3.2-stage_Darwin_x86_64.tar.gz"
      sha256 "bf8cd60ff28fdd723006702f4870cec14e204fa4026f7c35977e6f2d0ac1b6b7"

      def install
        bin.install "astrocloud"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v1.3.2-stage/cloud-cli_1.3.2-stage_Linux_arm64.tar.gz"
      sha256 "a7786355eee30ee3046ce238d82742d797fa7c914ea601de66840d1ed35f213f"

      def install
        bin.install "astrocloud"
      end
    end
    if Hardware::CPU.intel?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v1.3.2-stage/cloud-cli_1.3.2-stage_Linux_x86_64.tar.gz"
      sha256 "c103eccb3e55f5c04ff0c51a7231763e949cff833eb946007e6014ddec9a95aa"

      def install
        bin.install "astrocloud"
      end
    end
  end

  test do
    system "#{bin}/astrocloud version"
  end
end
