# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AstrocloudAT003Alpha < Formula
  desc "To build and run Airflow DAGs locally, deploy DAGs to the Astronomer Cloud and interact with the Astronomer API."
  homepage "https://astronomer.io"
  version "0.0.3-alpha"
  
  on_macos do
    if Hardware::CPU.arm?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v0.0.3-alpha/cloud-cli_0.0.3-alpha_Darwin_arm64.tar.gz"
      sha256 "cf8168a9162eb39046c18b8530c4ec06e610f49aa1094c77bea1e509c6fdbe30"

      def install
        bin.install "astrocloud"
      end
    end
    if Hardware::CPU.intel?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v0.0.3-alpha/cloud-cli_0.0.3-alpha_Darwin_x86_64.tar.gz"
      sha256 "ffa5719a47a789d05c5ca5a8f814af8bc7a2ed3d90ba5b568d9b7a93968589c9"

      def install
        bin.install "astrocloud"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v0.0.3-alpha/cloud-cli_0.0.3-alpha_Linux_arm64.tar.gz"
      sha256 "fc96839bc1d5adab5606dec16a0266febac76860a30c0d77468fb5b47134509d"

      def install
        bin.install "astrocloud"
      end
    end
    if Hardware::CPU.intel?
      url "https://goreleaserdev.blob.core.windows.net/goreleaser-test-container/releases/v0.0.3-alpha/cloud-cli_0.0.3-alpha_Linux_x86_64.tar.gz"
      sha256 "41e4658fc23f382caf17305ad2214fc4bb88c56da551829f6829d3bf5c3efc05"

      def install
        bin.install "astrocloud"
      end
    end
  end

  test do
    system "#{bin}/astrocloud version"
  end
end
